// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN9irn87lv8XsIc5ywpShQu0foeeUtxpM',
    appId: '1:833393742315:web:7c035b03bab1b9b34149ae',
    messagingSenderId: '833393742315',
    projectId: 'xceltoqr',
    authDomain: 'xceltoqr.firebaseapp.com',
    storageBucket: 'xceltoqr.firebasestorage.app',
    measurementId: 'G-FEYWMPFTWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzfvqECEtr6eN-TZ12lhnduXaigdvqTkk',
    appId: '1:833393742315:android:2820bdfd68bf255d4149ae',
    messagingSenderId: '833393742315',
    projectId: 'xceltoqr',
    storageBucket: 'xceltoqr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABNlE4AvI3_N-HXrbJIRRkq08GJHsLiSU',
    appId: '1:833393742315:ios:679de08c5c89cbdb4149ae',
    messagingSenderId: '833393742315',
    projectId: 'xceltoqr',
    storageBucket: 'xceltoqr.firebasestorage.app',
    iosBundleId: 'com.example.excelToBarcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABNlE4AvI3_N-HXrbJIRRkq08GJHsLiSU',
    appId: '1:833393742315:ios:679de08c5c89cbdb4149ae',
    messagingSenderId: '833393742315',
    projectId: 'xceltoqr',
    storageBucket: 'xceltoqr.firebasestorage.app',
    iosBundleId: 'com.example.excelToBarcode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN9irn87lv8XsIc5ywpShQu0foeeUtxpM',
    appId: '1:833393742315:web:3e57a350629a14584149ae',
    messagingSenderId: '833393742315',
    projectId: 'xceltoqr',
    authDomain: 'xceltoqr.firebaseapp.com',
    storageBucket: 'xceltoqr.firebasestorage.app',
    measurementId: 'G-S9PP42CCDK',
  );
}
